import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/Header'
import { Roboto } from 'next/font/google'
import { getServerSession } from 'next-auth'
import Link from 'next/link'
import Logout from './components/Logout'

const roboto = Roboto({
  subsets: ['latin', 'cyrillic'],
  weight: ['300', '400', '500', '700']
})

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await getServerSession()
  console.log(session);
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        {
          !session && <Link href="/login">войти в аккаунт</Link>
        }

        {
          !!session && <Logout />
        }
        <main>{children}</main>
      </body>
    </html>
  )
}
